version: '3.7'

services:
  api:
    container_name: api_movies
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 127.0.0.1:${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - postgres
      - redis

  redis:
    container_name: api_movies_redis
    image: redis:alpine
    ports:
      - 6379:6379
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - backend
    volumes:
      - redis_data:/data

  postgres:
    container_name: base_api_movies_db
    image: postgres:16-alpine
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 127.0.0.1:5434:5432
    volumes:
      - api_db_data:/var/lib/postgresql/data
networks:
  backend:
volumes:
  api_db_data:
  redis_data:
