version: '3.7'

services:
  api:
    restart: always
    container_name: api_movies
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: production
    volumes:
      - ./uploads:/usr/src/app/uploads
    ports:
      - 127.0.0.1:${API_PORT}:${API_PORT}
    env_file:
      - .env
    command: sh -c "yarn db:run && yarn start:prod"
    depends_on:
      - postgres
      - redis

  redis:
    restart: always
    container_name: api_movies_redis
    image: redis:alpine
    ports:
      - 127.0.0.1:6379:6379
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - backend
    volumes:
      - redis_data:/data

  postgres:
    container_name: base_api_movies_db
    image: postgres:16-alpine
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 127.0.0.1:5434:5432
    volumes:
      - api_db_data:/var/lib/postgresql/data
networks:
  backend:
volumes:
  api_db_data:
  redis_data:
