export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';

export const USER_EXIST = 'USER_EXIST';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const USER_PASSWORD_EMPTY = 'USER_PASSWORD_EMPTY';
export const USER_ROLE_NOT_FOUND = 'USER_ROLE_NOT_FOUND';
export const USER_UNAUTHORIZED = 'USER_UNAUTHORIZED';

export const DUPLICATE_EMAIL = 'DUPLICATE_EMAIL';
